#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKiTucXa
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLKiTucXa")]
	public partial class QLKTXDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertHOADONTIENDIEN(HOADONTIENDIEN instance);
    partial void UpdateHOADONTIENDIEN(HOADONTIENDIEN instance);
    partial void DeleteHOADONTIENDIEN(HOADONTIENDIEN instance);
    partial void InsertHOADONTIENPHONG(HOADONTIENPHONG instance);
    partial void UpdateHOADONTIENPHONG(HOADONTIENPHONG instance);
    partial void DeleteHOADONTIENPHONG(HOADONTIENPHONG instance);
    partial void InsertHOPDONG(HOPDONG instance);
    partial void UpdateHOPDONG(HOPDONG instance);
    partial void DeleteHOPDONG(HOPDONG instance);
    partial void InsertKHU(KHU instance);
    partial void UpdateKHU(KHU instance);
    partial void DeleteKHU(KHU instance);
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    partial void InsertSINHVIEN(SINHVIEN instance);
    partial void UpdateSINHVIEN(SINHVIEN instance);
    partial void DeleteSINHVIEN(SINHVIEN instance);
    partial void InsertPHONG(PHONG instance);
    partial void UpdatePHONG(PHONG instance);
    partial void DeletePHONG(PHONG instance);
    partial void InsertCONGTODIEN(CONGTODIEN instance);
    partial void UpdateCONGTODIEN(CONGTODIEN instance);
    partial void DeleteCONGTODIEN(CONGTODIEN instance);
    #endregion
		
		public QLKTXDataContext() : 
				base(global::QLKiTucXa.Properties.Settings.Default.QLKiTucXaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLKTXDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLKTXDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLKTXDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLKTXDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<HOADONTIENDIEN> HOADONTIENDIENs
		{
			get
			{
				return this.GetTable<HOADONTIENDIEN>();
			}
		}
		
		public System.Data.Linq.Table<HOADONTIENPHONG> HOADONTIENPHONGs
		{
			get
			{
				return this.GetTable<HOADONTIENPHONG>();
			}
		}
		
		public System.Data.Linq.Table<HOPDONG> HOPDONGs
		{
			get
			{
				return this.GetTable<HOPDONG>();
			}
		}
		
		public System.Data.Linq.Table<KHU> KHUs
		{
			get
			{
				return this.GetTable<KHU>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<SINHVIEN> SINHVIENs
		{
			get
			{
				return this.GetTable<SINHVIEN>();
			}
		}
		
		public System.Data.Linq.Table<PHONG> PHONGs
		{
			get
			{
				return this.GetTable<PHONG>();
			}
		}
		
		public System.Data.Linq.Table<CONGTODIEN> CONGTODIENs
		{
			get
			{
				return this.GetTable<CONGTODIEN>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOADONTIENDIEN")]
	public partial class HOADONTIENDIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _sohd;
		
		private string _maphong;
		
		private string _manv;
		
		private string _macongto;
		
		private System.Nullable<System.DateTime> _ngaylaphd;
		
		private System.Nullable<System.DateTime> _ngayghi;
		
		private System.Nullable<int> _chisodau;
		
		private System.Nullable<int> _chisocuoi;
		
		private System.Nullable<decimal> _tongtien;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
		private EntityRef<PHONG> _PHONG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsohdChanging(string value);
    partial void OnsohdChanged();
    partial void OnmaphongChanging(string value);
    partial void OnmaphongChanged();
    partial void OnmanvChanging(string value);
    partial void OnmanvChanged();
    partial void OnmacongtoChanging(string value);
    partial void OnmacongtoChanged();
    partial void OnngaylaphdChanging(System.Nullable<System.DateTime> value);
    partial void OnngaylaphdChanged();
    partial void OnngayghiChanging(System.Nullable<System.DateTime> value);
    partial void OnngayghiChanged();
    partial void OnchisodauChanging(System.Nullable<int> value);
    partial void OnchisodauChanged();
    partial void OnchisocuoiChanging(System.Nullable<int> value);
    partial void OnchisocuoiChanged();
    partial void OntongtienChanging(System.Nullable<decimal> value);
    partial void OntongtienChanged();
    #endregion
		
		public HOADONTIENDIEN()
		{
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			this._PHONG = default(EntityRef<PHONG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sohd", DbType="VarChar(13) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string sohd
		{
			get
			{
				return this._sohd;
			}
			set
			{
				if ((this._sohd != value))
				{
					this.OnsohdChanging(value);
					this.SendPropertyChanging();
					this._sohd = value;
					this.SendPropertyChanged("sohd");
					this.OnsohdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphong", DbType="VarChar(5)")]
		public string maphong
		{
			get
			{
				return this._maphong;
			}
			set
			{
				if ((this._maphong != value))
				{
					if (this._PHONG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaphongChanging(value);
					this.SendPropertyChanging();
					this._maphong = value;
					this.SendPropertyChanged("maphong");
					this.OnmaphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manv", DbType="VarChar(6)")]
		public string manv
		{
			get
			{
				return this._manv;
			}
			set
			{
				if ((this._manv != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmanvChanging(value);
					this.SendPropertyChanging();
					this._manv = value;
					this.SendPropertyChanged("manv");
					this.OnmanvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_macongto", DbType="VarChar(6)")]
		public string macongto
		{
			get
			{
				return this._macongto;
			}
			set
			{
				if ((this._macongto != value))
				{
					this.OnmacongtoChanging(value);
					this.SendPropertyChanging();
					this._macongto = value;
					this.SendPropertyChanged("macongto");
					this.OnmacongtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaylaphd", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaylaphd
		{
			get
			{
				return this._ngaylaphd;
			}
			set
			{
				if ((this._ngaylaphd != value))
				{
					this.OnngaylaphdChanging(value);
					this.SendPropertyChanging();
					this._ngaylaphd = value;
					this.SendPropertyChanged("ngaylaphd");
					this.OnngaylaphdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayghi", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayghi
		{
			get
			{
				return this._ngayghi;
			}
			set
			{
				if ((this._ngayghi != value))
				{
					this.OnngayghiChanging(value);
					this.SendPropertyChanging();
					this._ngayghi = value;
					this.SendPropertyChanged("ngayghi");
					this.OnngayghiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chisodau", DbType="Int")]
		public System.Nullable<int> chisodau
		{
			get
			{
				return this._chisodau;
			}
			set
			{
				if ((this._chisodau != value))
				{
					this.OnchisodauChanging(value);
					this.SendPropertyChanging();
					this._chisodau = value;
					this.SendPropertyChanged("chisodau");
					this.OnchisodauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chisocuoi", DbType="Int")]
		public System.Nullable<int> chisocuoi
		{
			get
			{
				return this._chisocuoi;
			}
			set
			{
				if ((this._chisocuoi != value))
				{
					this.OnchisocuoiChanging(value);
					this.SendPropertyChanging();
					this._chisocuoi = value;
					this.SendPropertyChanged("chisocuoi");
					this.OnchisocuoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongtien", DbType="Money")]
		public System.Nullable<decimal> tongtien
		{
			get
			{
				return this._tongtien;
			}
			set
			{
				if ((this._tongtien != value))
				{
					this.OntongtienChanging(value);
					this.SendPropertyChanging();
					this._tongtien = value;
					this.SendPropertyChanged("tongtien");
					this.OntongtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_HOADONTIENDIEN", Storage="_NHANVIEN", ThisKey="manv", OtherKey="manv", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.HOADONTIENDIENs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.HOADONTIENDIENs.Add(this);
						this._manv = value.manv;
					}
					else
					{
						this._manv = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONG_HOADONTIENDIEN", Storage="_PHONG", ThisKey="maphong", OtherKey="maphong", IsForeignKey=true)]
		public PHONG PHONG
		{
			get
			{
				return this._PHONG.Entity;
			}
			set
			{
				PHONG previousValue = this._PHONG.Entity;
				if (((previousValue != value) 
							|| (this._PHONG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHONG.Entity = null;
						previousValue.HOADONTIENDIENs.Remove(this);
					}
					this._PHONG.Entity = value;
					if ((value != null))
					{
						value.HOADONTIENDIENs.Add(this);
						this._maphong = value.maphong;
					}
					else
					{
						this._maphong = default(string);
					}
					this.SendPropertyChanged("PHONG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOADONTIENPHONG")]
	public partial class HOADONTIENPHONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _sohd;
		
		private string _masv;
		
		private System.Nullable<System.DateTime> _ngaylaphd;
		
		private string _manv;
		
		private System.Nullable<System.DateTime> _ngaybatdau;
		
		private System.Nullable<System.DateTime> _ngayketthuc;
		
		private System.Nullable<decimal> _tongtien;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
		private EntityRef<SINHVIEN> _SINHVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsohdChanging(string value);
    partial void OnsohdChanged();
    partial void OnmasvChanging(string value);
    partial void OnmasvChanged();
    partial void OnngaylaphdChanging(System.Nullable<System.DateTime> value);
    partial void OnngaylaphdChanged();
    partial void OnmanvChanging(string value);
    partial void OnmanvChanged();
    partial void OnngaybatdauChanging(System.Nullable<System.DateTime> value);
    partial void OnngaybatdauChanged();
    partial void OnngayketthucChanging(System.Nullable<System.DateTime> value);
    partial void OnngayketthucChanged();
    partial void OntongtienChanging(System.Nullable<decimal> value);
    partial void OntongtienChanged();
    #endregion
		
		public HOADONTIENPHONG()
		{
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			this._SINHVIEN = default(EntityRef<SINHVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sohd", DbType="Char(13) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string sohd
		{
			get
			{
				return this._sohd;
			}
			set
			{
				if ((this._sohd != value))
				{
					this.OnsohdChanging(value);
					this.SendPropertyChanging();
					this._sohd = value;
					this.SendPropertyChanged("sohd");
					this.OnsohdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masv", DbType="VarChar(11)")]
		public string masv
		{
			get
			{
				return this._masv;
			}
			set
			{
				if ((this._masv != value))
				{
					if (this._SINHVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmasvChanging(value);
					this.SendPropertyChanging();
					this._masv = value;
					this.SendPropertyChanged("masv");
					this.OnmasvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaylaphd", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaylaphd
		{
			get
			{
				return this._ngaylaphd;
			}
			set
			{
				if ((this._ngaylaphd != value))
				{
					this.OnngaylaphdChanging(value);
					this.SendPropertyChanging();
					this._ngaylaphd = value;
					this.SendPropertyChanged("ngaylaphd");
					this.OnngaylaphdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manv", DbType="VarChar(6)")]
		public string manv
		{
			get
			{
				return this._manv;
			}
			set
			{
				if ((this._manv != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmanvChanging(value);
					this.SendPropertyChanging();
					this._manv = value;
					this.SendPropertyChanged("manv");
					this.OnmanvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaybatdau", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaybatdau
		{
			get
			{
				return this._ngaybatdau;
			}
			set
			{
				if ((this._ngaybatdau != value))
				{
					this.OnngaybatdauChanging(value);
					this.SendPropertyChanging();
					this._ngaybatdau = value;
					this.SendPropertyChanged("ngaybatdau");
					this.OnngaybatdauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayketthuc", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayketthuc
		{
			get
			{
				return this._ngayketthuc;
			}
			set
			{
				if ((this._ngayketthuc != value))
				{
					this.OnngayketthucChanging(value);
					this.SendPropertyChanging();
					this._ngayketthuc = value;
					this.SendPropertyChanged("ngayketthuc");
					this.OnngayketthucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongtien", DbType="Money")]
		public System.Nullable<decimal> tongtien
		{
			get
			{
				return this._tongtien;
			}
			set
			{
				if ((this._tongtien != value))
				{
					this.OntongtienChanging(value);
					this.SendPropertyChanging();
					this._tongtien = value;
					this.SendPropertyChanged("tongtien");
					this.OntongtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_HOADONTIENPHONG", Storage="_NHANVIEN", ThisKey="manv", OtherKey="manv", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.HOADONTIENPHONGs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.HOADONTIENPHONGs.Add(this);
						this._manv = value.manv;
					}
					else
					{
						this._manv = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SINHVIEN_HOADONTIENPHONG", Storage="_SINHVIEN", ThisKey="masv", OtherKey="masv", IsForeignKey=true)]
		public SINHVIEN SINHVIEN
		{
			get
			{
				return this._SINHVIEN.Entity;
			}
			set
			{
				SINHVIEN previousValue = this._SINHVIEN.Entity;
				if (((previousValue != value) 
							|| (this._SINHVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SINHVIEN.Entity = null;
						previousValue.HOADONTIENPHONGs.Remove(this);
					}
					this._SINHVIEN.Entity = value;
					if ((value != null))
					{
						value.HOADONTIENPHONGs.Add(this);
						this._masv = value.masv;
					}
					else
					{
						this._masv = default(string);
					}
					this.SendPropertyChanged("SINHVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOPDONG")]
	public partial class HOPDONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _mahd;
		
		private string _masv;
		
		private string _manv;
		
		private System.Nullable<System.DateTime> _ngaybd;
		
		private System.Nullable<System.DateTime> _ngaykt;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
		private EntityRef<SINHVIEN> _SINHVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmahdChanging(string value);
    partial void OnmahdChanged();
    partial void OnmasvChanging(string value);
    partial void OnmasvChanged();
    partial void OnmanvChanging(string value);
    partial void OnmanvChanged();
    partial void OnngaybdChanging(System.Nullable<System.DateTime> value);
    partial void OnngaybdChanged();
    partial void OnngayktChanging(System.Nullable<System.DateTime> value);
    partial void OnngayktChanged();
    #endregion
		
		public HOPDONG()
		{
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			this._SINHVIEN = default(EntityRef<SINHVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mahd", DbType="VarChar(13) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mahd
		{
			get
			{
				return this._mahd;
			}
			set
			{
				if ((this._mahd != value))
				{
					this.OnmahdChanging(value);
					this.SendPropertyChanging();
					this._mahd = value;
					this.SendPropertyChanged("mahd");
					this.OnmahdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masv", DbType="VarChar(11)")]
		public string masv
		{
			get
			{
				return this._masv;
			}
			set
			{
				if ((this._masv != value))
				{
					if (this._SINHVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmasvChanging(value);
					this.SendPropertyChanging();
					this._masv = value;
					this.SendPropertyChanged("masv");
					this.OnmasvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manv", DbType="VarChar(6)")]
		public string manv
		{
			get
			{
				return this._manv;
			}
			set
			{
				if ((this._manv != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmanvChanging(value);
					this.SendPropertyChanging();
					this._manv = value;
					this.SendPropertyChanged("manv");
					this.OnmanvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaybd", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaybd
		{
			get
			{
				return this._ngaybd;
			}
			set
			{
				if ((this._ngaybd != value))
				{
					this.OnngaybdChanging(value);
					this.SendPropertyChanging();
					this._ngaybd = value;
					this.SendPropertyChanged("ngaybd");
					this.OnngaybdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaykt", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaykt
		{
			get
			{
				return this._ngaykt;
			}
			set
			{
				if ((this._ngaykt != value))
				{
					this.OnngayktChanging(value);
					this.SendPropertyChanging();
					this._ngaykt = value;
					this.SendPropertyChanged("ngaykt");
					this.OnngayktChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_HOPDONG", Storage="_NHANVIEN", ThisKey="manv", OtherKey="manv", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.HOPDONGs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.HOPDONGs.Add(this);
						this._manv = value.manv;
					}
					else
					{
						this._manv = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SINHVIEN_HOPDONG", Storage="_SINHVIEN", ThisKey="masv", OtherKey="masv", IsForeignKey=true)]
		public SINHVIEN SINHVIEN
		{
			get
			{
				return this._SINHVIEN.Entity;
			}
			set
			{
				SINHVIEN previousValue = this._SINHVIEN.Entity;
				if (((previousValue != value) 
							|| (this._SINHVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SINHVIEN.Entity = null;
						previousValue.HOPDONGs.Remove(this);
					}
					this._SINHVIEN.Entity = value;
					if ((value != null))
					{
						value.HOPDONGs.Add(this);
						this._masv = value.masv;
					}
					else
					{
						this._masv = default(string);
					}
					this.SendPropertyChanged("SINHVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHU")]
	public partial class KHU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _makhu;
		
		private string _tenkhu;
		
		private System.Nullable<int> _soluongtoida;
		
		private EntitySet<PHONG> _PHONGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmakhuChanging(string value);
    partial void OnmakhuChanged();
    partial void OntenkhuChanging(string value);
    partial void OntenkhuChanged();
    partial void OnsoluongtoidaChanging(System.Nullable<int> value);
    partial void OnsoluongtoidaChanged();
    #endregion
		
		public KHU()
		{
			this._PHONGs = new EntitySet<PHONG>(new Action<PHONG>(this.attach_PHONGs), new Action<PHONG>(this.detach_PHONGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makhu", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string makhu
		{
			get
			{
				return this._makhu;
			}
			set
			{
				if ((this._makhu != value))
				{
					this.OnmakhuChanging(value);
					this.SendPropertyChanging();
					this._makhu = value;
					this.SendPropertyChanged("makhu");
					this.OnmakhuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenkhu", DbType="NVarChar(20)")]
		public string tenkhu
		{
			get
			{
				return this._tenkhu;
			}
			set
			{
				if ((this._tenkhu != value))
				{
					this.OntenkhuChanging(value);
					this.SendPropertyChanging();
					this._tenkhu = value;
					this.SendPropertyChanged("tenkhu");
					this.OntenkhuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluongtoida", DbType="Int")]
		public System.Nullable<int> soluongtoida
		{
			get
			{
				return this._soluongtoida;
			}
			set
			{
				if ((this._soluongtoida != value))
				{
					this.OnsoluongtoidaChanging(value);
					this.SendPropertyChanging();
					this._soluongtoida = value;
					this.SendPropertyChanged("soluongtoida");
					this.OnsoluongtoidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHU_PHONG", Storage="_PHONGs", ThisKey="makhu", OtherKey="makhu")]
		public EntitySet<PHONG> PHONGs
		{
			get
			{
				return this._PHONGs;
			}
			set
			{
				this._PHONGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHONGs(PHONG entity)
		{
			this.SendPropertyChanging();
			entity.KHU = this;
		}
		
		private void detach_PHONGs(PHONG entity)
		{
			this.SendPropertyChanging();
			entity.KHU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _manv;
		
		private string _tennv;
		
		private System.Nullable<System.DateTime> _ngaysinh;
		
		private System.Nullable<bool> _gioitinh;
		
		private string _diachi;
		
		private string _dienthoai;
		
		private EntitySet<HOADONTIENDIEN> _HOADONTIENDIENs;
		
		private EntitySet<HOADONTIENPHONG> _HOADONTIENPHONGs;
		
		private EntitySet<HOPDONG> _HOPDONGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmanvChanging(string value);
    partial void OnmanvChanged();
    partial void OntennvChanging(string value);
    partial void OntennvChanged();
    partial void OnngaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaysinhChanged();
    partial void OngioitinhChanging(System.Nullable<bool> value);
    partial void OngioitinhChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OndienthoaiChanging(string value);
    partial void OndienthoaiChanged();
    #endregion
		
		public NHANVIEN()
		{
			this._HOADONTIENDIENs = new EntitySet<HOADONTIENDIEN>(new Action<HOADONTIENDIEN>(this.attach_HOADONTIENDIENs), new Action<HOADONTIENDIEN>(this.detach_HOADONTIENDIENs));
			this._HOADONTIENPHONGs = new EntitySet<HOADONTIENPHONG>(new Action<HOADONTIENPHONG>(this.attach_HOADONTIENPHONGs), new Action<HOADONTIENPHONG>(this.detach_HOADONTIENPHONGs));
			this._HOPDONGs = new EntitySet<HOPDONG>(new Action<HOPDONG>(this.attach_HOPDONGs), new Action<HOPDONG>(this.detach_HOPDONGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manv", DbType="VarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string manv
		{
			get
			{
				return this._manv;
			}
			set
			{
				if ((this._manv != value))
				{
					this.OnmanvChanging(value);
					this.SendPropertyChanging();
					this._manv = value;
					this.SendPropertyChanged("manv");
					this.OnmanvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tennv", DbType="NVarChar(30)")]
		public string tennv
		{
			get
			{
				return this._tennv;
			}
			set
			{
				if ((this._tennv != value))
				{
					this.OntennvChanging(value);
					this.SendPropertyChanging();
					this._tennv = value;
					this.SendPropertyChanged("tennv");
					this.OntennvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="Bit")]
		public System.Nullable<bool> gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(50)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dienthoai", DbType="Char(10)")]
		public string dienthoai
		{
			get
			{
				return this._dienthoai;
			}
			set
			{
				if ((this._dienthoai != value))
				{
					this.OndienthoaiChanging(value);
					this.SendPropertyChanging();
					this._dienthoai = value;
					this.SendPropertyChanged("dienthoai");
					this.OndienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_HOADONTIENDIEN", Storage="_HOADONTIENDIENs", ThisKey="manv", OtherKey="manv")]
		public EntitySet<HOADONTIENDIEN> HOADONTIENDIENs
		{
			get
			{
				return this._HOADONTIENDIENs;
			}
			set
			{
				this._HOADONTIENDIENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_HOADONTIENPHONG", Storage="_HOADONTIENPHONGs", ThisKey="manv", OtherKey="manv")]
		public EntitySet<HOADONTIENPHONG> HOADONTIENPHONGs
		{
			get
			{
				return this._HOADONTIENPHONGs;
			}
			set
			{
				this._HOADONTIENPHONGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_HOPDONG", Storage="_HOPDONGs", ThisKey="manv", OtherKey="manv")]
		public EntitySet<HOPDONG> HOPDONGs
		{
			get
			{
				return this._HOPDONGs;
			}
			set
			{
				this._HOPDONGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOADONTIENDIENs(HOADONTIENDIEN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_HOADONTIENDIENs(HOADONTIENDIEN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
		
		private void attach_HOADONTIENPHONGs(HOADONTIENPHONG entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_HOADONTIENPHONGs(HOADONTIENPHONG entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
		
		private void attach_HOPDONGs(HOPDONG entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_HOPDONGs(HOPDONG entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SINHVIEN")]
	public partial class SINHVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _masv;
		
		private string _maphong;
		
		private string _tensv;
		
		private System.Nullable<System.DateTime> _ngaysinh;
		
		private System.Nullable<bool> _gioitinh;
		
		private string _lop;
		
		private string _dienthoai;
		
		private string _quequan;
		
		private System.Nullable<bool> _tinhtrang;
		
		private EntitySet<HOADONTIENPHONG> _HOADONTIENPHONGs;
		
		private EntitySet<HOPDONG> _HOPDONGs;
		
		private EntityRef<PHONG> _PHONG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmasvChanging(string value);
    partial void OnmasvChanged();
    partial void OnmaphongChanging(string value);
    partial void OnmaphongChanged();
    partial void OntensvChanging(string value);
    partial void OntensvChanged();
    partial void OnngaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaysinhChanged();
    partial void OngioitinhChanging(System.Nullable<bool> value);
    partial void OngioitinhChanged();
    partial void OnlopChanging(string value);
    partial void OnlopChanged();
    partial void OndienthoaiChanging(string value);
    partial void OndienthoaiChanged();
    partial void OnquequanChanging(string value);
    partial void OnquequanChanged();
    partial void OntinhtrangChanging(System.Nullable<bool> value);
    partial void OntinhtrangChanged();
    #endregion
		
		public SINHVIEN()
		{
			this._HOADONTIENPHONGs = new EntitySet<HOADONTIENPHONG>(new Action<HOADONTIENPHONG>(this.attach_HOADONTIENPHONGs), new Action<HOADONTIENPHONG>(this.detach_HOADONTIENPHONGs));
			this._HOPDONGs = new EntitySet<HOPDONG>(new Action<HOPDONG>(this.attach_HOPDONGs), new Action<HOPDONG>(this.detach_HOPDONGs));
			this._PHONG = default(EntityRef<PHONG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masv", DbType="VarChar(11) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string masv
		{
			get
			{
				return this._masv;
			}
			set
			{
				if ((this._masv != value))
				{
					this.OnmasvChanging(value);
					this.SendPropertyChanging();
					this._masv = value;
					this.SendPropertyChanged("masv");
					this.OnmasvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphong", DbType="VarChar(5)")]
		public string maphong
		{
			get
			{
				return this._maphong;
			}
			set
			{
				if ((this._maphong != value))
				{
					if (this._PHONG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaphongChanging(value);
					this.SendPropertyChanging();
					this._maphong = value;
					this.SendPropertyChanged("maphong");
					this.OnmaphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tensv", DbType="NVarChar(30)")]
		public string tensv
		{
			get
			{
				return this._tensv;
			}
			set
			{
				if ((this._tensv != value))
				{
					this.OntensvChanging(value);
					this.SendPropertyChanging();
					this._tensv = value;
					this.SendPropertyChanged("tensv");
					this.OntensvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="Bit")]
		public System.Nullable<bool> gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lop", DbType="Char(10)")]
		public string lop
		{
			get
			{
				return this._lop;
			}
			set
			{
				if ((this._lop != value))
				{
					this.OnlopChanging(value);
					this.SendPropertyChanging();
					this._lop = value;
					this.SendPropertyChanged("lop");
					this.OnlopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dienthoai", DbType="Char(10)")]
		public string dienthoai
		{
			get
			{
				return this._dienthoai;
			}
			set
			{
				if ((this._dienthoai != value))
				{
					this.OndienthoaiChanging(value);
					this.SendPropertyChanging();
					this._dienthoai = value;
					this.SendPropertyChanged("dienthoai");
					this.OndienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quequan", DbType="NVarChar(50)")]
		public string quequan
		{
			get
			{
				return this._quequan;
			}
			set
			{
				if ((this._quequan != value))
				{
					this.OnquequanChanging(value);
					this.SendPropertyChanging();
					this._quequan = value;
					this.SendPropertyChanged("quequan");
					this.OnquequanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhtrang", DbType="Bit")]
		public System.Nullable<bool> tinhtrang
		{
			get
			{
				return this._tinhtrang;
			}
			set
			{
				if ((this._tinhtrang != value))
				{
					this.OntinhtrangChanging(value);
					this.SendPropertyChanging();
					this._tinhtrang = value;
					this.SendPropertyChanged("tinhtrang");
					this.OntinhtrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SINHVIEN_HOADONTIENPHONG", Storage="_HOADONTIENPHONGs", ThisKey="masv", OtherKey="masv")]
		public EntitySet<HOADONTIENPHONG> HOADONTIENPHONGs
		{
			get
			{
				return this._HOADONTIENPHONGs;
			}
			set
			{
				this._HOADONTIENPHONGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SINHVIEN_HOPDONG", Storage="_HOPDONGs", ThisKey="masv", OtherKey="masv")]
		public EntitySet<HOPDONG> HOPDONGs
		{
			get
			{
				return this._HOPDONGs;
			}
			set
			{
				this._HOPDONGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONG_SINHVIEN", Storage="_PHONG", ThisKey="maphong", OtherKey="maphong", IsForeignKey=true)]
		public PHONG PHONG
		{
			get
			{
				return this._PHONG.Entity;
			}
			set
			{
				PHONG previousValue = this._PHONG.Entity;
				if (((previousValue != value) 
							|| (this._PHONG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHONG.Entity = null;
						previousValue.SINHVIENs.Remove(this);
					}
					this._PHONG.Entity = value;
					if ((value != null))
					{
						value.SINHVIENs.Add(this);
						this._maphong = value.maphong;
					}
					else
					{
						this._maphong = default(string);
					}
					this.SendPropertyChanged("PHONG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOADONTIENPHONGs(HOADONTIENPHONG entity)
		{
			this.SendPropertyChanging();
			entity.SINHVIEN = this;
		}
		
		private void detach_HOADONTIENPHONGs(HOADONTIENPHONG entity)
		{
			this.SendPropertyChanging();
			entity.SINHVIEN = null;
		}
		
		private void attach_HOPDONGs(HOPDONG entity)
		{
			this.SendPropertyChanging();
			entity.SINHVIEN = this;
		}
		
		private void detach_HOPDONGs(HOPDONG entity)
		{
			this.SendPropertyChanging();
			entity.SINHVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHONG")]
	public partial class PHONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maphong;
		
		private string _macongto;
		
		private string _makhu;
		
		private System.Nullable<int> _soluong;
		
		private System.Nullable<bool> _tinhtrang;
		
		private EntitySet<HOADONTIENDIEN> _HOADONTIENDIENs;
		
		private EntitySet<SINHVIEN> _SINHVIENs;
		
		private EntityRef<KHU> _KHU;
		
		private EntityRef<CONGTODIEN> _CONGTODIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaphongChanging(string value);
    partial void OnmaphongChanged();
    partial void OnmacongtoChanging(string value);
    partial void OnmacongtoChanged();
    partial void OnmakhuChanging(string value);
    partial void OnmakhuChanged();
    partial void OnsoluongChanging(System.Nullable<int> value);
    partial void OnsoluongChanged();
    partial void OntinhtrangChanging(System.Nullable<bool> value);
    partial void OntinhtrangChanged();
    #endregion
		
		public PHONG()
		{
			this._HOADONTIENDIENs = new EntitySet<HOADONTIENDIEN>(new Action<HOADONTIENDIEN>(this.attach_HOADONTIENDIENs), new Action<HOADONTIENDIEN>(this.detach_HOADONTIENDIENs));
			this._SINHVIENs = new EntitySet<SINHVIEN>(new Action<SINHVIEN>(this.attach_SINHVIENs), new Action<SINHVIEN>(this.detach_SINHVIENs));
			this._KHU = default(EntityRef<KHU>);
			this._CONGTODIEN = default(EntityRef<CONGTODIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphong", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maphong
		{
			get
			{
				return this._maphong;
			}
			set
			{
				if ((this._maphong != value))
				{
					this.OnmaphongChanging(value);
					this.SendPropertyChanging();
					this._maphong = value;
					this.SendPropertyChanged("maphong");
					this.OnmaphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_macongto", DbType="VarChar(6)")]
		public string macongto
		{
			get
			{
				return this._macongto;
			}
			set
			{
				if ((this._macongto != value))
				{
					if (this._CONGTODIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmacongtoChanging(value);
					this.SendPropertyChanging();
					this._macongto = value;
					this.SendPropertyChanged("macongto");
					this.OnmacongtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makhu", DbType="VarChar(2)")]
		public string makhu
		{
			get
			{
				return this._makhu;
			}
			set
			{
				if ((this._makhu != value))
				{
					if (this._KHU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmakhuChanging(value);
					this.SendPropertyChanging();
					this._makhu = value;
					this.SendPropertyChanged("makhu");
					this.OnmakhuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int")]
		public System.Nullable<int> soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this.OnsoluongChanging(value);
					this.SendPropertyChanging();
					this._soluong = value;
					this.SendPropertyChanged("soluong");
					this.OnsoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhtrang", DbType="Bit")]
		public System.Nullable<bool> tinhtrang
		{
			get
			{
				return this._tinhtrang;
			}
			set
			{
				if ((this._tinhtrang != value))
				{
					this.OntinhtrangChanging(value);
					this.SendPropertyChanging();
					this._tinhtrang = value;
					this.SendPropertyChanged("tinhtrang");
					this.OntinhtrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONG_HOADONTIENDIEN", Storage="_HOADONTIENDIENs", ThisKey="maphong", OtherKey="maphong")]
		public EntitySet<HOADONTIENDIEN> HOADONTIENDIENs
		{
			get
			{
				return this._HOADONTIENDIENs;
			}
			set
			{
				this._HOADONTIENDIENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONG_SINHVIEN", Storage="_SINHVIENs", ThisKey="maphong", OtherKey="maphong")]
		public EntitySet<SINHVIEN> SINHVIENs
		{
			get
			{
				return this._SINHVIENs;
			}
			set
			{
				this._SINHVIENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHU_PHONG", Storage="_KHU", ThisKey="makhu", OtherKey="makhu", IsForeignKey=true)]
		public KHU KHU
		{
			get
			{
				return this._KHU.Entity;
			}
			set
			{
				KHU previousValue = this._KHU.Entity;
				if (((previousValue != value) 
							|| (this._KHU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHU.Entity = null;
						previousValue.PHONGs.Remove(this);
					}
					this._KHU.Entity = value;
					if ((value != null))
					{
						value.PHONGs.Add(this);
						this._makhu = value.makhu;
					}
					else
					{
						this._makhu = default(string);
					}
					this.SendPropertyChanged("KHU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CONGTODIEN_PHONG", Storage="_CONGTODIEN", ThisKey="macongto", OtherKey="macongto", IsForeignKey=true)]
		public CONGTODIEN CONGTODIEN
		{
			get
			{
				return this._CONGTODIEN.Entity;
			}
			set
			{
				CONGTODIEN previousValue = this._CONGTODIEN.Entity;
				if (((previousValue != value) 
							|| (this._CONGTODIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CONGTODIEN.Entity = null;
						previousValue.PHONGs.Remove(this);
					}
					this._CONGTODIEN.Entity = value;
					if ((value != null))
					{
						value.PHONGs.Add(this);
						this._macongto = value.macongto;
					}
					else
					{
						this._macongto = default(string);
					}
					this.SendPropertyChanged("CONGTODIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOADONTIENDIENs(HOADONTIENDIEN entity)
		{
			this.SendPropertyChanging();
			entity.PHONG = this;
		}
		
		private void detach_HOADONTIENDIENs(HOADONTIENDIEN entity)
		{
			this.SendPropertyChanging();
			entity.PHONG = null;
		}
		
		private void attach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.PHONG = this;
		}
		
		private void detach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.PHONG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CONGTODIEN")]
	public partial class CONGTODIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _macongto;
		
		private System.Nullable<System.DateTime> _ngaylapdat;
		
		private System.Nullable<bool> _tinhtrang;
		
		private EntitySet<PHONG> _PHONGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmacongtoChanging(string value);
    partial void OnmacongtoChanged();
    partial void OnngaylapdatChanging(System.Nullable<System.DateTime> value);
    partial void OnngaylapdatChanged();
    partial void OntinhtrangChanging(System.Nullable<bool> value);
    partial void OntinhtrangChanged();
    #endregion
		
		public CONGTODIEN()
		{
			this._PHONGs = new EntitySet<PHONG>(new Action<PHONG>(this.attach_PHONGs), new Action<PHONG>(this.detach_PHONGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_macongto", DbType="VarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string macongto
		{
			get
			{
				return this._macongto;
			}
			set
			{
				if ((this._macongto != value))
				{
					this.OnmacongtoChanging(value);
					this.SendPropertyChanging();
					this._macongto = value;
					this.SendPropertyChanged("macongto");
					this.OnmacongtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaylapdat", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaylapdat
		{
			get
			{
				return this._ngaylapdat;
			}
			set
			{
				if ((this._ngaylapdat != value))
				{
					this.OnngaylapdatChanging(value);
					this.SendPropertyChanging();
					this._ngaylapdat = value;
					this.SendPropertyChanged("ngaylapdat");
					this.OnngaylapdatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhtrang", DbType="Bit")]
		public System.Nullable<bool> tinhtrang
		{
			get
			{
				return this._tinhtrang;
			}
			set
			{
				if ((this._tinhtrang != value))
				{
					this.OntinhtrangChanging(value);
					this.SendPropertyChanging();
					this._tinhtrang = value;
					this.SendPropertyChanged("tinhtrang");
					this.OntinhtrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CONGTODIEN_PHONG", Storage="_PHONGs", ThisKey="macongto", OtherKey="macongto")]
		public EntitySet<PHONG> PHONGs
		{
			get
			{
				return this._PHONGs;
			}
			set
			{
				this._PHONGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHONGs(PHONG entity)
		{
			this.SendPropertyChanging();
			entity.CONGTODIEN = this;
		}
		
		private void detach_PHONGs(PHONG entity)
		{
			this.SendPropertyChanging();
			entity.CONGTODIEN = null;
		}
	}
}
#pragma warning restore 1591
